/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'root' at '4/27/17 7:37 PM' with Gradle 3.0
 *
 * @author root, @date 4/27/17 7:37 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
